version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cp-reminder-bot
    restart: always
    env_file:
      - .env
    ports:
      - '3334:3334'
